---
title: "Unicef Data Viz"
format: html
editor: visual
---

## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
# install.packages(c("ggplot2","dplyr","rnaturalearth","plotly"))
library(rnaturalearth)
```

## Bar Chart

```{r}
library(ggplot2)
unicef_indicator <- read.csv("./unicef_indicator.csv")

data = unicef_indicator[unicef_indicator$time_period > 2003 & unicef_indicator$time_period < 2012, ]

ggplot(data, aes(x=time_period, y=obs_value, fill = sex)) +
  geom_bar(position = "stack",
           stat = "summary",
           fun = "mean")

```

## Scatter Plot

```{r}
library(ggplot2)
library(dplyr)

data2 = unicef_indicator[unicef_indicator$time_period > 2003 & unicef_indicator$time_period < 2012, ]

data3 <- data2 %>%
  group_by(time_period)%>%
  summarize(mean=mean(obs_value))

ggplot(unicef_indicator,aes(x=as.numeric(time_period),y=as.numeric(obs_value))) +
  geom_point(color='red') +
  geom_smooth(method = 'lm') +
  xlab("Year") + ylab("Observation Value")
  

```

## World Map

```{r}
# Load required libraries
library(rnaturalearth)

library(plotly)
library(dplyr)

# Load viridis package for additional color palettes
# install.packages("viridis")
library(viridis)

# Get a spatial dataset of country boundaries
world_map <- ne_countries(scale = "medium", returnclass = "sf")

# Assign the main dataset to a new variable with a simpler name
main_data <- `unicef_indicator`
library(rnaturalearth)

# Merge the main dataset (main_data) with the world_map dataset
merged_data <- world_map %>%
  left_join(main_data, by = c("name" = "country"))

# Create a ggplot object with merged_data
world_map_plot <- ggplot(data = merged_data) +
  geom_sf(aes(fill = obs_value, text = paste("Obs_value:", obs_value, "<br>Country:", name)), size = 0.1) +
  theme_minimal() +
  scale_fill_viridis_c(option = "A", direction = -1, trans = "log", 
                       name = "Observation\nValue", labels = scales::comma, end = 0.9) +
  labs()


# Convert to interactive plotly object
interactive_world_map <- ggplotly(world_map_plot)

# Include the interactive plot in R Markdown document
interactive_world_map
```

## Time series Chart

```{r}
library(ggplot2)
library(dplyr)

data3 <- unicef_indicator %>%
  group_by(time_period)%>%
  summarize(mean=mean(obs_value))

# Most basic bubble plot
ggplot(unicef_indicator, aes(x=time_period, y=obs_value, group = country, colour = country)) +
  geom_line()

```
